# Generated by Django 2.1.5 on 2019-04-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190403_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
