# Generated by Django 2.1.5 on 2019-04-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofileinfo_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='bio',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
