# Generated by Django 2.1.5 on 2019-04-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190410_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSurveyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorites', models.TextField(blank=True, max_length=100)),
            ],
        ),
    ]
