# Generated by Django 2.1.5 on 2019-04-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_usersurveyinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSurveyInfo',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='favorites',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
