# Generated by Django 2.1.5 on 2019-04-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190421_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='S', max_length=1),
        ),
    ]
