# Generated by Django 2.1.5 on 2019-04-21 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofileinfo_shirt_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='shirt_size',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='smoking',
            field=models.CharField(choices=[('Y', 'Smoking'), ('N', 'No Smoking')], default='N', max_length=1),
        ),
    ]
