# Generated by Django 2.1.5 on 2019-04-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190421_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='favorites',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='age',
            field=models.IntegerField(default=18, max_length=2),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unspecified')], default='U', max_length=1),
        ),
    ]
