# Generated by Django 2.1.5 on 2019-04-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190421_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='class_year',
            field=models.CharField(default='FR', max_length=2),
        ),
    ]
