# Generated by Django 2.1.5 on 2019-04-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20190422_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', help_text='Profile Picture', null=True, upload_to='profile_pics', verbose_name='Profile Picture'),
        ),
    ]
