# Generated by Django 2.1.5 on 2019-04-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20190422_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='image_width',
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
