# Generated by Django 2.1.5 on 2019-04-24 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20190424_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='Dorm_Choice_Second',
            new_name='Dorm_Choice_Two',
        ),
    ]
