# Generated by Django 2.1.5 on 2019-04-24 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20190424_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='bed',
            new_name='Sleeping_Habits',
        ),
    ]
