# Generated by Django 2.1.5 on 2019-04-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_userprofileinfo_cleanliness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='cleanliness',
            field=models.IntegerField(blank=True, max_length=2),
        ),
    ]
