# Generated by Django 2.1.5 on 2019-04-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20190424_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='cleanliness',
            field=models.IntegerField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')], max_length=2),
        ),
    ]
