# Generated by Django 2.1.5 on 2019-04-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20190424_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='matching',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
